sudo:
  - false

language:
  - cpp

cache:
  directories:
    - odb

matrix:
  include:

      # OS X
    - os: osx
      osx_image: xcode9.3
      env: C_COMPILER=clang CXX_COMPILER=clang++
      before_install:
        - brew install ninja
        - brew install boost@1.55
        - brew link --overwrite --force boost@1.55

      # OS X
    - os: osx
      osx_image: xcode9.3
      env: C_COMPILER=gcc CXX_COMPILER=g++
      before_install:
        - brew install ninja
        - brew install boost@1.55
        - brew link --overwrite --force boost@1.55

    # Clang 4.0
    - os: linux
      compiler: clang
      env: C_COMPILER=clang-4.0 CXX_COMPILER=clang++-4.0
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-iostreams1.55-dev
            - libboost-program-options1.55-dev
            - libboost-regex1.55-dev
            - libboost-log1.55-dev
            - ninja-build

    # Clang 5.0
    - os: linux
      compiler: clang
      env: C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-iostreams1.55-dev
            - libboost-program-options1.55-dev
            - libboost-regex1.55-dev
            - libboost-log1.55-dev
            - ninja-build

    # GCC 4.8
    - os: linux
      compiler: gcc
      env: C_COMPILER=gcc-4.8 CXX_COMPILER=g++-4.8
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-iostreams1.55-dev
            - libboost-program-options1.55-dev
            - libboost-regex1.55-dev
            - libboost-log1.55-dev
            - ninja-build


    # GCC 5
    - os: linux
      compiler: gcc
      env: C_COMPILER=gcc-5 CXX_COMPILER=g++-5
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-iostreams1.55-dev
            - libboost-program-options1.55-dev
            - libboost-regex1.55-dev
            - libboost-log1.55-dev
            - ninja-build

    # GCC 6
    - os: linux
      compiler: gcc
      env: C_COMPILER=gcc-6 CXX_COMPILER=g++-6
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-iostreams1.55-dev
            - libboost-program-options1.55-dev
            - libboost-regex1.55-dev
            - libboost-log1.55-dev
            - ninja-build


before_script:
  - echo "installing libodb"
  - mkdir -p odb && cd odb
  - wget http://codesynthesis.com/download/odb/2.4/libodb-2.4.0.tar.bz2 -O /tmp/libodb.tar.bz2
  - tar jxvf /tmp/libodb.tar.bz2
  - cd libodb-2.4.0 && ./configure && make
  - cd ..

  - echo "installing libodb-sqlite"
  - wget http://codesynthesis.com/download/odb/2.4/libodb-sqlite-2.4.0.tar.bz2 -O /tmp/libodb-sqlite.tar.bz2
  - tar jxvf /tmp/libodb-sqlite.tar.bz2
  - cd libodb-sqlite-2.4.0 && ./configure --with-libodb=../libodb-2.4.0 && make
  - cd ..

  - pwd
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      cp libodb-2.4.0/odb/.libs/libodb.a .
      cp libodb-sqlite-2.4.0/odb/sqlite/.libs/libodb-sqlite.a .

      cp libodb-2.4.0/odb/.libs/libodb.so .
      cp libodb-sqlite-2.4.0/odb/sqlite/.libs/libodb-sqlite.so .


      wget http://codesynthesis.com/download/odb/2.4/odb-2.4.0-x86_64-linux-gnu.tar.bz2 -O /tmp/odb.tar.bz2
      tar jxvf /tmp/odb.tar.bz2
      export PATH=$PATH:$PWD/odb-2.4.0-x86_64-linux-gnu/bin/
    fi
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      cp libodb-2.4.0/odb/.libs/libodb.a .
      cp libodb-sqlite-2.4.0/odb/sqlite/.libs/libodb-sqlite.a .

      cp libodb-2.4.0/odb/.libs/libodb.dylib .
      cp libodb-sqlite-2.4.0/odb/sqlite/.libs/libodb-sqlite.dylib .


      wget http://codesynthesis.com/download/odb/2.4/odb-2.4.0-i686-macosx.tar.bz2 -O /tmp/odb.tar.bz2
      tar jxvf /tmp/odb.tar.bz2
      export PATH=$PATH:$PWD/odb-2.4.0-i686-macosx/bin/
    fi
  - cd ..

  - echo "downloaded odb:"
  - echo $PATH
  - ls odb


script:
  - cmake -DBUILD_STATIC=0 -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_FLAGS="-Iodb/libodb-2.4.0 -Iodb/libodb-sqlite-2.4.0" -DCMAKE_EXE_LINKER_FLAGS="-Wl,-rpath,odb/ -Lodb/"  -DODB_PATH=$PWD/odb/ ./ -GNinja
  - ninja -v -j2
  - ninja test
