sudo:
  - false

language:
  - cpp

cache:
  directories:
    - linux_dependencies
    - osx_dependencies

matrix:
  include:

    # OS X Clang
    - os: osx
      osx_image: xcode9.3
      env: C_COMPILER=clang CXX_COMPILER=clang++
      before_install:
        - brew install ninja

    # OS X GCC
    - os: osx
      osx_image: xcode9.3
      env: C_COMPILER=gcc CXX_COMPILER=g++
      before_install:
        - brew install ninja

    # Clang 4.0
    - os: linux
      compiler: clang
      env: C_COMPILER=clang-4.0 CXX_COMPILER=clang++-4.0
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-iostreams1.55-dev
            - libboost-program-options1.55-dev
            - libboost-regex1.55-dev
            - libboost-log1.55-dev
            - ninja-build

    # Clang 5.0
    - os: linux
      compiler: clang
      env: C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-iostreams1.55-dev
            - libboost-program-options1.55-dev
            - libboost-regex1.55-dev
            - libboost-log1.55-dev
            - ninja-build

    # GCC 4.8
    - os: linux
      compiler: gcc
      env: C_COMPILER=gcc-4.8 CXX_COMPILER=g++-4.8
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-iostreams1.55-dev
            - libboost-program-options1.55-dev
            - libboost-regex1.55-dev
            - libboost-log1.55-dev
            - ninja-build

    # GCC 5
    - os: linux
      compiler: gcc
      env: C_COMPILER=gcc-5 CXX_COMPILER=g++-5
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-iostreams1.55-dev
            - libboost-program-options1.55-dev
            - libboost-regex1.55-dev
            - libboost-log1.55-dev
            - ninja-build

    # GCC 6
    - os: linux
      compiler: gcc
      env: C_COMPILER=gcc-6 CXX_COMPILER=g++-6
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-iostreams1.55-dev
            - libboost-program-options1.55-dev
            - libboost-regex1.55-dev
            - libboost-log1.55-dev
            - ninja-build


before_script:
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      ./install_dependencies.sh
    fi
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      ./install_dependencies.sh osx
    fi


script:
  - cmake -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_C_COMPILER=${C_COMPILER} ./ -GNinja
  - ninja -v -j2
  - ninja test
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      otool -L bin/vcf_validator
    fi

deploy:
  provider: releases
  api_key:
    secure: bUBg9U1QvPmRS+xMlv2Nm3JNi6SqFh8PDfkz2hAH978gp6MEgtNKG/P84gWoTSnUhO/FfblBBESbVgTslzHMy1G5JGrc8hkm29Wc19wq8oxQyTeK1l3GX8BXPbmGjY7a2ybidcMgC+fvK3rKDf0db3QBM/3BF8sezh4UoCkuq8i9u1NyGAyioeSZzVHHpIDVEtHjr9MqAwDtPFE/2HvIInovfFYXJhTaQTZTU8Jc6ITfxY5q+HtvZ+2h4bZiIs2BgBP2KJY88QMXIYkxKKsTMrFeB9Ysijl2Bb+i55tfe6NBVkYC8k8/h/Sun5XhfhlUV1A0FMRkerOCvVFsV1Il0B/Ldjt0Cdw2l3/eezM3yZhFX+QUfZJSq1WwemXQQjlL4DmtjcP84WP6xk3cYZfEN0A/BXcdHP1l83vQXT3xaQ0dwLzA/6igOE6sHODhbeuBxl25psypen56jqVhj6erU/bM3ZqW+o8hOuMnVi2JeJ0cEGfU5Dgo8oxIHdSzks6kpxRIDMF9ciVOKNYA0T8H4R812xu4St2ijPQVz+EOcE8s1rHbA/8XPf2a9fdWkndY8tUq0lV+senf5CxLBof9t4442z7eEtPhJm0tcaoHX6gKhW8gGYlvqX0zykPE1qa3UQ2Eec6NLBKErVThEgblsuv6wG/VwfSV7SuIjAw/6sg=
  file:
    - bin/vcf_validator
    - bin/vcf_debugulator
  skip_cleanup:true
  on:
    repo: EBIvariation/vcf-validator
    branch: release/0.9