os:
  - Visual Studio 2017

init:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cmd: set INCLUDE=C:\Libraries\boost_1_67_0;%INCLUDE%
  - cmd: set LIB=C:\Libraries\boost_1_67_0\lib32-msvc-14.1;%LIB%
  - cmd: set PATH=C:\projects\vcf-validator\lib\windows_specific;%PATH%

install:
  - cmd: install_dependencies.bat

build_script:
  - cmd: if not exist build mkdir build
  - cmd: cd build
  - cmd: cmake -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ..
  - cmd: nmake
  - cmd: cd ..

test_script:
  - cmd: build\bin\test_validator.exe
  - cmd: build\bin\test_validator_v41.exe
  - cmd: build\bin\test_validator_v42.exe
  - cmd: build\bin\test_validator_v43.exe

artifacts:
  - path: build\bin\vcf_validator.exe
    name: vcf_validator_win.exe

  - path: build\bin\vcf_debugulator.exe
    name: vcf_debugulator_win.exe

cache:
  - build
